### ISSUE TITLE
Добавить тень панели задач

### ISSUE THREAD

**Issue by Animalfox** [Animalfox/GreenShell#9]
Совсем забыл, что в гайдлайне она есть. Белые приложения сливаются с белой панелью задач, это надо поправить.

**Comment by PeyTy** [comment]
А тень рендерится системно или лайтстепом?

**Comment by Animalfox** [comment]
Тень рендерится лайтстепом. Как обычная графика. Всё кешировано и нисколько ресурсов не кушается. Ни озу / ни цп. Пространство заполненное спрайтом поверх обычных окон (не игровых).
